### ISSUE TITLE
json.decoder.JSONDecodeError error on api startup

### ISSUE THREAD

**Issue by camisetags** [sixcodes/brandenburg#13]
<img width="1008" alt="Screen Shot 2020-06-23 at 00 32 49" src="https://user-images.githubusercontent.com/5252228/85358373-eb859000-b4e9-11ea-9a91-d5929b335068.png">

**Comment by jesuejunior** [comment]
I have to doc what is the basic configuration to be set. this error is about GCP credentials. 
It should be fixed using the ENV VARSs with these configurations. However, it should try to check local credentials also.

**Comment by jesuejunior** [comment]
Solved, it was a problem with google credentials configuration. The new doc will cover this step.
